name: Build and Deploy

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21.6'

      - name: Install dependencies
        run: |
          go mod tidy

      - name: Build
        run: |
          go build -o myapp ./cmd/web  # Replace 'myapp' with your executable name and './cmd/myapp' with your main package path

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
    
          publish_dir: ./UB-Campus-Safety  # Change this to your build output directory
          user_name: MtechGuy 
          user_email: 2020152022@ub.edu.bz
          publish_branch: gh-pages
